{
 "title": "Meshtastic Telemetry (Net)",
 "time": { "from": "now-6h", "to": "now" },
 "refresh": "30s",
 "templating": {
  "list": [
   {
    "name": "source",
    "query": {
     "query": "label_values(meshtastic_mesh_packets_total,source_long_name)"
    }
   }
  ]
 },
 "panels": [
  {
   "title": "Battery level",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "avg_over_time(meshtastic_telemetry_device_battery_level_percent{source_long_name=~\"$source\"}[$__interval])",
     "legendFormat": "{{source_long_name}} ({{source}})"
    }
   ]
  },
  {
   "title": "Temperature",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "celsius" } },
   "targets": [
    {
     "expr": "avg_over_time(meshtastic_telemetry_env_temperature_celsius{source_long_name=~\"$source\"}[$__interval])",
     "legendFormat": "{{source_long_name}} ({{source}})"
    }
   ]
  },
  {
   "title": "Barometric pressure",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "mmHg" } },
   "targets": [
    {
     "expr": "avg_over_time(meshtastic_telemetry_env_barometric_pressure_pascal {source_long_name=~\"$source\"}[$__interval]) / 133.3",
     "legendFormat": "{{source_long_name}} ({{source}})"
    }
   ]
  },
  {
   "title": "Channel util",
   "type": "timeseries",
   "gridPos": { "h": 16, "w": 12, "x": 0, "y": 17 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "avg_over_time(meshtastic_telemetry_device_channel_utilization_percent{source_long_name=~\"$source\"}[$__interval])",
     "legendFormat": "{{source_long_name}} ({{source}})"
    }
   ]
  },
  {
   "title": "Air util tx",
   "type": "timeseries",
   "gridPos": { "h": 16, "w": 12, "x": 12, "y": 17 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "avg_over_time(meshtastic_telemetry_device_air_util_tx_percent{source_long_name=~\"$source\"}[$__interval])",
     "legendFormat": "{{source_long_name}} ({{source}})"
    }
   ]
  },
  {
   "title": "Sats in View",
   "type": "timeseries",
   "gridPos": { "x": 0, "y": 40, "h": 8, "w": 12 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "avg_over_time(meshtastic_position_sats_in_view{source_long_name=~\"$source\"}[$__interval])",
     "legendFormat": "{{source_long_name}} ({{source}})"
    }
   ]
  },
  {
   "title": "Dilution of Precision (DOP)",
   "type": "timeseries",
   "description": "Combined graph of HDOP/PDOP (and VDOP if it exists)",
   "gridPos": { "x": 12, "y": 40, "h": 8, "w": 12 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "avg_over_time(meshtastic_position_hdop{source_long_name=~\"$source\"}[$__interval])",
     "legendFormat": "{{source_long_name}} ({{source}})"
    },
    {
     "expr": "avg_over_time(meshtastic_position_pdop{source_long_name=~\"$source\"}[$__interval])",
     "legendFormat": "{{source_long_name}} ({{source}})"
    }
   ]
  },
  {
   "title": "Environment Voltage",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 33 },
   "fieldConfig": { "defaults": { "unit": "volt" } },
   "targets": [
    {
     "expr": "avg_over_time(meshtastic_telemetry_env_voltage_volts{source_long_name=~\"$source\"}[$__interval])",
     "legendFormat": "{{source_long_name}} ({{source}})"
    }
   ]
  },
  {
   "title": "Environment Current",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 33 },
   "fieldConfig": { "defaults": { "unit": "amp" } },
   "targets": [
    {
     "expr": "avg_over_time(meshtastic_telemetry_env_current_amperes{source_long_name=~\"$source\"}[$__interval])",
     "legendFormat": "{{source_long_name}} ({{source}})"
    }
   ]
  }
 ]
}